### ISSUE TITLE
FR: Include DIGEST header and appropriate values for HTTP responses that include a file stream for downloading

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#10]
When streaming files from endpoints such as notes, it would be advantageous to have a hashsum value included in the `DIGEST` header of the response to facilitate confirmation that the file has been downloaded correctly/is the expected file.

**Comment by scottetass** [comment]
Hi,

Thanks for the suggestion.

> **Benefits of Including a Digest Header**
> 
> - Data Integrity: The Digest header allows the client to verify that the file has not been altered during transmission. This is particularly important for large files or files downloaded over unreliable networks.
> 
> - Security: It adds an extra layer of security by ensuring that the file received is exactly what the server intended to send, protecting against tampering or corruption.
> 
> **Considerations**
> 
> - Performance: Calculating the checksum for large files can be resource-intensive.



The next build will contain the Digest header in the response.

![image](https://github.com/user-attachments/assets/7baf5e7f-0be8-4125-b3bd-e66f71e8ab6c)

Thanks, Scott

**Comment by redtrinity** [comment]
Thanks Scott, much appreciated.

**Comment by redtrinity** [comment]
For clarification, will the generated hash of the file per `sha-256=` be the literal SHA or will it be encoded using something like base64 or other?

**Comment by scottetass** [comment]
Hi,

The hash is base64 encoded, so you'll need to convert that before checking the hash is correct.
I'll add something to the documentation to clarify that.

Thanks, Scott

**Comment by redtrinity** [comment]
Confirming DIGEST value returned in headers and working as expected.
