### ISSUE TITLE
FR: Include an optional Usage Description field for API user accounts

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#12]
It would be helpful to include an optional `Usage Description` field for user accounts created in the new API user management system. This would allow a comment to be added that briefly describes what that account was created for so that any future review of user accounts will have some context to what the account is for.

For example, noting an account was created to sync between a specifc system and TASS.

![Screen_Shot_2024-12-12-105417-158773](https://github.com/user-attachments/assets/8fb1961b-888d-4c48-8b94-dbb42e8433bb)

**Comment by scottetass** [comment]
Hi,

This has been done and will be available in the next build (#5300).

A new field has been added to the user screen as per below.

![image](https://github.com/user-attachments/assets/657a4561-41d4-468e-be1f-d4560a769e81)

Thanks, Scott
