### ISSUE TITLE
FR: Document any information about generated token expirations

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#2]
The documentation about the token generated during authentication process doesn't indicate if the token will expire after a TTL period (and the JSON response doesn't indicate any TTL/expiration time), it would be helpful to know if the token expires after a given period of time, and if it does, include that value in JSON response so handling token renewal can be achieved.

**Comment by scottetass** [comment]
Hi,

The token expiry is set to 15 minutes. I'll update the documentation to reflect that.

I'll make a change to either return the expiry date in the payload or as a response header.

Thanks, Scott

**Comment by redtrinity** [comment]
My preference would be it forms part of the payload sent from the auth process.

**Comment by scottetass** [comment]
The expiry date will be returned in the payload like below. The date will be in UTC format to avoid time zone issues.

![image](https://github.com/user-attachments/assets/533468f0-d8c0-49f8-9663-2eb87009894f)

If you call the API with an expired token, by default, there will be response headers with expiry information:

![image](https://github.com/user-attachments/assets/690079dc-46d6-406e-a063-a67b7b21e025)

This will be in the next build.

**Comment by redtrinity** [comment]
Fantastic :)
