### ISSUE TITLE
FR: Provide some sample OData for filtering, patching etc

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#4]
It would be helpful to have some OData samples for PATCH's in the documentation, as OData has a different PATCH style compared to some other API systems where JSON can be sent with just the key value pairs that are being patched.

**Comment by scottetass** [comment]
See this explanation [here.](https://github.com/TheAlphaSchoolSystemPTYLTD/APIBetaTesting/issues/5)

PATCH uses a JSON syntax for providing details in the body, it's a bit more complicated than providing a key/value pair. This is normal behavior for a REST API, explanations and links to check out in the thread linked above.

Let me know if you have any further questions.

**Comment by scottetass** [comment]
Further to this, I've included some some sample oData usage in the 'Introduction' page. This should be available in the next build.
