### ISSUE TITLE
API Validation Issue for Employee records

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#7]
When submitting an update to an employee address, some errors are raised for fields that are not being updated.
In the example below, only the `add1_text` value is being updated, however the API responds with a validation error for the `phone_w_text` field.

Additionally a `Company is disabled` error is thrown regarding `cmpy_code` however the company code is being provided in the URL path.

Note: We store a three digit extension in the `phone_w_text` field to denote the internal extension of the employee, we do not store the phone number in full. When modifying the address in TASS itself, no validation error is thrown.

The employee code in this output has been sanitised with `emp_code`.

```
[sanitised@osiris]:Desktop # ./tass_api_beta.py
@request args=('emp_code/information',), kwargs={'json': [{'op': 'replace', 'path': 'add1_text', 'value': 'Test School'}]}
{'User-Agent': 'sanitised/api-beta/v1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer sanitised'}
@request url='https://tass-test.sanitised.qld.edu.au/api/01/employee/emp_code/information'
Traceback (most recent call last):
  File "/Users/sanitised/Desktop/./tass_api_beta.py", line 36, in <module>
    r = e.patch_employee("emp_code", json=[{"op": "replace", "path": "add1_text", "value": "Test School"}])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanitised/Library/Python/site-packages/tassbeta/endpoints/employees.py", line 31, in patch_employee
    return self.patch(f"{emp_code}/information", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanitised/Library/Python/site-packages/tassbeta/decorators.py", line 56, in wrapped
    return parse_response(resp)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanitised/Library/Python/site-packages/tassbeta/utils.py", line 97, in parse_response
    raise APIResponseException(msg)
tassbeta.api_exceptions.APIResponseException: Error: Validation errors have occurred. 
cmpy_code: ['Company is disabled.']
phone_w_text: ['phone_w_text is not a valid phone number.']
```

Providing the company code and employee code being updated in the `path` parameter in the JSON yields (as does other variations of):

```
tassbeta.api_exceptions.APIResponseException: Error: Validation errors have occurred. 
01.emp_code.add1_text: ['Field is invalid for this endpoint.']
```

Including `from` in the JSON:
```
@request args=('emp_code/information',), kwargs={'json': [{'op': 'replace', 'path': '/add1_text', 'from': 'Old Address', 'value': 'Address Line 1 String'}]}
@request url='https://tass-test.redlands.qld.edu.au/api/01/employee/emp_code/information'
...
tassbeta.api_exceptions.APIResponseException: Error: Validation errors have occurred. 
Old Address: ['Field is invalid for this endpoint.']
```

**Comment by scottetass** [comment]
Hi,

'Company is disabled' - this error is raised because the company is flagged as permanently disabled. Can you please check the company setup to ensure this is not the case. We are blocking adding/updating employee records for companies that are no longer enabled. This mimics the behaviour in TASS.web where you can't even work in a company if its disabled (although we have left the ability to read data from disabled companies in the API).

'phone_w_text is not a valid phone number.' - I'll remove the validation from this field and other phone fields in the next build. We are currently validating whether the nok_phone_h_text, nok_phone_w_text, phone_h_text, phone_w_text and mob_phone are actual phone numbers but looks like we can't enforce that as previous validation in TASS doesn't do that.

The last two errors are because the employee code and company code shouldn't be provided in the JSON. The 'path' property should only point to a valid field in the request, anything else will get you the error you are seeing.

Thanks, Scott

**Comment by redtrinity** [comment]
This is the API setup. We only have the one company code - 10 and 11 are disabled in our company setup.

![Screen_Shot_2024-12-02-080633-034258](https://github.com/user-attachments/assets/5af2ca29-c3e5-4aad-826b-bfff11fba35d)

![Screen_Shot_2024-12-02-081008-818483](https://github.com/user-attachments/assets/fa16b630-14a3-4a6a-96cb-22d274d97a86)

**Comment by scottetass** [comment]
I've found the problem with the 'company is not enabled' error. A fix will be in the next build. I'll try to get this done as quick as possible and let you know when a new build is available for updating your test environment.

**Comment by redtrinity** [comment]
After sorting out the date format provided, these were the last two attributes that returned an error if no value was provided.

```
tassbeta.api_exceptions.APIResponseException: Error: Validation errors have occurred. 
deceased_flg: ['deceased_flg value is invalid, it must be one of N or Y.']
sms_flg: ['sms_flg value is invalid, it must be one of N or Y.']
```

Both of these are not strictly required fields in TASS itself,  both `deceased_flg` and `sms_flg` default to a value of 'N' when creating an employee record; could the API default to setting that to `N` if a value is not provided - or within the documentation indicate that an `N` or `Y` value is required?

**Comment by scottetass** [comment]
No problem.

I'll make them default to 'N' if not provided and remove the 'required' flag if they have it. If something is provided, it will follow validation rules of it needing to be Y or N.

This should be in the next build.

Thanks, Scott

**Comment by redtrinity** [comment]
Fantastic - thanks Scott :)

**Comment by redtrinity** [comment]
Confirming `deceased_flg` and `sms_flg` defaulting to `N` when no value is provided is working.
